### ISSUE TITLE
Issue with where() causing exception

### ISSUE THREAD

**Issue by svgaman** [nilportugues/php-sql-query-builder#66]
Hello,
When i add the clause where() to a query (tested with select and update) i got an exception

### EXCEPTION
>Argument 1 passed to NilPortugues\Sql\QueryBuilder\Builder\GenericBuilder::write() must implement interface NilPortugues\Sql\QueryBuilder\Manipulation\QueryInterface, instance of NilPortugues\Sql\QueryBuilder\Syntax\Where given, called in xxxxxxxxx

### OK
```
$builder = new \NilPortugues\Sql\QueryBuilder\Builder\GenericBuilder(); 
$q1 = $builder->select()->setTable($tableName);    
$sql = $builder->write($q1);
```

### NOT OK
```
$builder = new \NilPortugues\Sql\QueryBuilder\Builder\GenericBuilder(); 
$q1 = $builder->select()->setTable($tableName)->where()->equals('id', 1);    
$sql = $builder->write($q1);
```

Any ideas ?

**Comment by nilopc** [comment]
Looks like a bug to me..I'll tag it as such and look into it.

I'll keep you posted

**Comment by ericsicons** [comment]
Yup I wanted to use this script a while back but I also had the above issue.

**Comment by nilopc** [comment]
```
$builder = new \NilPortugues\Sql\QueryBuilder\Builder\GenericBuilder(); 
$q1 = $builder->select()->setTable($tableName);
$q1->where()->equals('id', 1);    

$sql = $builder->write($q1);
```

Works just fine. But I agree it does not feel as natural as just typing the query, that I assume it's your main concern. 

The reason this was done this way is because as a builder, it should not enforce order, therefore, ->limit() can be called before ->where(), for instance.

**Comment by svgaman** [comment]
Ok ! we need to build query in two pass :)
thank you for support
