### ISSUE TITLE
orderBy array

### ISSUE THREAD

**Issue by qlarin** [nilportugues/php-sql-query-builder#74]
I came across a problem with select query. When i have tried to join two different tables to sort some results, i couldn't get correct sequence of 'order by' clause.
After analyzed, it seems that you split usual 'order by' from the one which is used in join. It is any chance to get correct sequence? I mean, i would like to get for example:

`order by 'table1.col1', 'table2.col1', 'table1.col2'`,

 but at the moment i have got something like:

`order by 'table1.col1', 'table1.col2', 'table2.col1'`.

**Comment by nilportugues** [comment]
Mind sharing the code used @qlarin ?

**Comment by qlarin** [comment]
The code which is responsible for orders it's really simple. Something like that:

protected function querySort(Query $query, $sorts = null)
{

}
