### ISSUE TITLE
Using it without Composer

### ISSUE THREAD

**Issue by belaarany** [nilportugues/php-sql-query-builder#94]
Hello,

Unfortunately I am not able to use Composer nor any autoload because of my hosting company's restrictions. So I should load all the files manually from a PHP file but when I try to do this it gives me errors like `Fatal error: Interface 'NilPortugues\Sql\QueryBuilder\Manipulation\QueryInterface' not found in ...`.

Can someone help me how to load it properly?

Thank you in advance!

**Comment by fridde** [comment]
Where do you develop your website? Hopefully on a local machine where you have all rights, right?

Whenever you run "composer update" or "require" or "install", an autoload mapping is created that tells PHP where to find all the classes that it does not recognize.

For example, it tells PHP that NilPortugues\Sql\QueryBuilder\Manipulation\QueryInterface can be found in vendor\nilportugues\sql-query-builder\src\Manipulation\QueryInterface.php 

So as long as you make sure to upload your whole vendor package and run ```require __DIR__.'/vendor/autoload.php'``` before everything else (for example in top of your index.php file), you should not need to be able to run composer on your server.

If your hosting company has disabled the actual function ```spl_autoload_register()``` they might be a VERY weird company and you should either have a talk with them or change host.

**Comment by belaarany** [comment]
Thank you for your answer! I am at a hosting company and composer is not allowed to be used unfortunately.

I installed composer on local host and checked it out and I have found that `vendor` folder. Is that would be enough to copy that folder to my web server?

**Comment by joseph-montanez** [comment]
@belaarany As long as you upload the `vendor` folder then you are good. However you should also upload composer.json and composer.lock to keep track of whats in the vendor folder. Any composer commands much be run locally.

**Comment by marcus-hiles** [comment]
Great, this post was helpful
