### ISSUE TITLE
Values in writed SQL 

### ISSUE THREAD

**Issue by darksoftware** [nilportugues/php-sql-query-builder#99]
Library generated sql template and values:

=== === === === === === === === === === === ===

`string 'SELECT `cd_documents`.* FROM `cd_documents` WHERE (`cd_documents`.`id` = :v1)' (length=77)`

```
array (size=1)
  ':v1' => string 'aaa' (length=3)
```

=== === === === === === === === === === === ===

How can I get the final SQL query with the values already set without automatic "external" functions? And substituted correctly, depending on the condition and type.

Or need to reinvent your "bike"?

In general, the library is excellent, but only this possibility is missing.

**Comment by Sevavietl** [comment]
Library generates SQL for [prepared statement](https://en.wikipedia.org/wiki/Prepared_statement). This means that query is never formed on PHP side, but instead executed on SQL side using binded values.

PHP [PDO](http://php.net/manual/en/book.pdo.php) works the same way.

While it is good feature for debugging, but it can be abused to use in production, providing a way for [SQL injection](https://en.wikipedia.org/wiki/SQL_injection).

If you want to see actual query one way would be to enable [mysql logs](https://dev.mysql.com/doc/refman/8.0/en/server-logs.html) (or some other RDMS).
